### ISSUE TITLE
'includeAll' cause infinite loop

### ISSUE THREAD

**Issue by StanislavIsaev** [jamesnetherton/wildfly-liquibase#59]
When changelog file has 'includeAll' tag - this causes an infinite loop.

Steps to reproduce:
1. Create jar with resources:
liquibase
--initial
  -- 01.xml
  -- 02.xml
--master-changelog.xml
2. master-changelog.xml contains:

`<includeAll path="liquibase/initial"/>`

3. Deploy jar to wildly (18.0.1.Final used)

liquibase.changelog.DatabaseChangeLog.includeAll calls 
`unsortedResources = resourceAccessor.list(relativeTo, pathName, true, false, true);`
with pathName='liquibase/initial'

https://github.com/jamesnetherton/wildfly-liquibase/blob/048ca637bc6484182eed1b89958a5a48c182d2eb/subsystem/src/main/java/com/github/jamesnetherton/extension/liquibase/service/ChangeLogExecutionService.java#L161
will always return Set with one value 'master-changelog.xml'.

**Comment by jamesnetherton** [comment]
Thanks for reporting this. It's obviously a bug.

Avoiding the infinite loop turned out to be simple, but `includeAll` seems to be having no affect for my test cases. 

The included change logs never seem to get executed. I see the same thing when I deploy a 'normal' Liquibase web application (E.g fat WAR, not using the subsystem). So I need to dig into it some more.
