### ISSUE TITLE
No ability to specify 'contexts' when deploying jar with *changelog.xml

### ISSUE THREAD

**Issue by StanislavIsaev** [jamesnetherton/wildfly-liquibase#60]
LiquibaseChangeLogParseProcessor doesn't set any contexts for ChangeLogConfiguration.

Maybe contexts should be resolved from env/sys properties as defaults.
E.g. for liquibase-maven-plugin it uses 'liquibase.contexts' property.

**Comment by jamesnetherton** [comment]
The problem with system properties is that they are set globally for the entire container. Env properties are also a bit problematic because the subsystem supports multiple change logs files within an individual deployment.

What I'm proposing to do is control this stuff via `jboss-all.xml`. For example:

```xml
<jboss xmlns="urn:jboss:1.0">
    <liquibase xmlns="urn:com.github.jamesnetherton.liquibase:1.0" changelog="changelog.xml">
        <contexts>context1,context2</contexts>
    </liquibase>
    <liquibase xmlns="urn:com.github.jamesnetherton.liquibase:1.0" changelog="otherchangelog.sql">
        <contexts>otherContext1,otherContext2</contexts>
    </liquibase>
</jboss>
```

Eventually I'll add support for all the various config Liquibase config properties.
